FROM mysql:latest

# Define variáveis de ambiente para a configuração do MySQL
ENV MYSQL_DATABASE database
ENV MYSQL_USER userDb
ENV MYSQL_PASSWORD password1234
ENV MYSQL_ROOT_PASSWORD password1234Root